# -*- coding: utf-8 -*-
"""streamlit-app.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HHqeiuvSmoGXziDmHCxiLYIsMG-rnyXo
"""

!pip install streamlit

import streamlit as st

def main():
    # Set the page title and icon
    st.set_page_config(
        page_title="Profile Page",
        page_icon="✅"
    )

    # Header section
    st.title("Profile Page")
    st.write("Welcome to your profile page!")

    # User input fields
    login = st.button("Login")
    quit_button = st.button("Quit")
    nama_mahasiswa = st.text_input("Nama Mahasiswa", "")

    # Body section
    st.header("Profile Information")
    nama = st.text_input("Nama", "")
    nomor_id = st.text_input("Nomor ID", "")
    pst = st.text_input("PST", "")

    # Display user inputs
    if login:
        st.write("User logged in!")
    if quit_button:
        st.write("User quit!")
    if nama_mahasiswa:
        st.write(f"Nama Mahasiswa: {nama_mahasiswa}")

    # Display profile information
    st.write(f"Nama: {nama}")
    st.write(f"Nomor ID: {nomor_id}")
    st.write(f"PST: {pst}")

if __name__ == "__main__":
    main()

streamlit run streamlit-app.py

