# -*- coding: utf-8 -*-
"""streamlit-app.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HHqeiuvSmoGXziDmHCxiLYIsMG-rnyXo
"""
!pip install pandas
import streamlit as st

st.write('Hello World')
